### ISSUE TITLE
README update load_restrictor should be load-restrictor (depending on versions)

### ISSUE THREAD

**Issue by chadmf** [redhat-cop/rhel-edge-automation-arch#134]
Just to keep track need to update documentation in README.md

```shell
kustomize build --load_restrictor=LoadRestrictionsNone openshift/gitops/clusters/overlays/byo/bootstrap/ | oc apply -f -
```

Should be:

```shell
kustomize build --load-restrictor=LoadRestrictionsNone openshift/gitops/clusters/overlays/byo/bootstrap/ | oc apply -f -
```

**Comment by sabre1041** [comment]
@chadmf which Kustomize version are you using?

**Comment by chadmf** [comment]
@sabre1041 {Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}

**Comment by pkliczewski** [comment]
Here is a [PR](https://github.com/redhat-cop/rhel-edge-automation-arch/pull/141) updating it to the kustomize latest(v4.3.0).
