### ISSUE TITLE
Sometimes ISO Pipeline has Certificate Validation Issues

### ISSUE THREAD

**Issue by nasx** [redhat-cop/rhel-edge-automation-arch#138]
Sometimes the task calling `composer-cli compose rhel-edge-installer` fails with certificate validation errors:

> `Get "https://httpd-rfe.apps.cluster.com/hello-world/latest/refs/heads/rhel/8/x86_64/edge": x509: certificate signed by unknown authority`

Options:
* Try https://github.com/osbuild/osbuild-composer/blob/main/internal/weldr/json.go#L143
* Extract ingress CA from OpenShift and add it to `image-builder` VM trust store

**Comment by sabre1041** [comment]
@nasx i'd like to embrace property security do that there is a trust between the `image-builder` and the `httpd` pod. One concern is how the truststore of the `image-builder` will be maintained over time. Will there be a routine job that will sync the certificates (in case it changes over time)?

**Comment by nasx** [comment]
Addressed in #226
