### ISSUE TITLE
Quay Registry Validation Fails During Quay Setup

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/rhel-edge-automation-arch#144]
During the setup of Quay, [conditional logic](https://github.com/redhat-cop/rhel-edge-automation-arch/blob/main/ansible/playbooks/quay-setup.yaml#L86) fails due to changes in the way the `QuayRegistry` CR status is populated. 

Change the logic to instead to use health check status of the Quay instance (`/health/instance`). An example of a healthy status is below:

```
{
  "data": {
    "services": {
      "auth": true,
      "database": true,
      "disk_space": true,
      "registry_gunicorn": true,
      "service_key": true,
      "web_gunicorn": true
    }
  },
  "status_code": 200
}
```

**Comment by nasx** [comment]
Fixed was merged. Closing this out.
