### ISSUE TITLE
updated readme to create symlink for ssh

### ISSUE THREAD

**Issue by chadhellyea** [redhat-cop/rhel-edge-automation-arch#61]
In the README it states you need Red Hat Portal Username, Password, Pool ID and Offline Token. the token contains all of this and is all that is needed.

Next, modify `openshift/gitops/clusters/overlays/byo/bootstrap/redhat-portal-credentials` and add the Red Hat Portal Username, Password, Pool ID and Offline Token to the appropriate variables. More information about generating an Offline Token can be found [here](https://access.redhat.com/articles/3626371).

Also instead of copying the ssh keys to a location I changed it to create a symlink instead.

**Comment by nasx** [comment]
I don't think you can register the image builder VM with the offline token. I also tried the symlink in the cloud config script and it didn't work for me hence the copy.

**Comment by nasx** [comment]
Disregard comment about symlink, I understand what you mean now.

**Comment by chadhellyea** [comment]
reverted the changes to the portal. we will need to figure that out for satellite users as most enterprise customers will be using a satellite.

**Comment by nasx** [comment]
The satellite integration w/ image builder is not there yet. There are some work arounds but when it works OOTB we can add support. Should be as simple as adding an Ansible task to grab http://satellite/pub/katello-ca-consumer-latest.noarch.rpm and install it.
