### ISSUE TITLE
rundex not found

### ISSUE THREAD

**Issue by mbach04** [redhat-cop/rhel-edge-automation-arch#66]
openshift-gitops-dex-server in crashloopbackoff with following error in the logs:
`Error: unknown command "rundex" for "argocd"
Run 'argocd --help' for usage.
time="2021-05-14T04:06:12Z" level=fatal msg="unknown command \"rundex\" for \"argocd\""`

**Comment by sabre1041** [comment]
Related to #67

**Comment by mbach04** [comment]
Note: issue only appears with openshift-gitops-operator.v1.0.0

**Comment by mbach04** [comment]
Source image for the error: quay.io/dexidp/dex@sha256:01e996b4b60edcc5cc042227c6965dd63ba68764c25d86b481b0d65f6e4da308

**Comment by sabre1041** [comment]
@mbach04 can this be closed?

**Comment by mbach04** [comment]
I think so, I've not seen this error with any of the recent deployments.
