### ISSUE TITLE
Update to GitOps Operator GA

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/rhel-edge-automation-arch#67]
Update to GitOps Operator GA release and associated dependencies and references

**Comment by mbach04** [comment]
@sabre1041 Is it more involved than the subscription update to openshift-gitops in PR 65?

**Comment by sabre1041** [comment]
@mbach04 yes there are multiple changes that are required (mainly related to GA):

1. GitOps operator uses a different namespace
2. GitOps operator is named differently
3. Process to enable OpenShift Authentication is different

Additional steps are needed to align with different namespace and SA that runs the application controller

**Comment by mbach04** [comment]
I see. I think 1 and 2 are minor, I could PR a fix for those if you'd like? Part 3 though would likely take me a fairly long time to investigate.

**Comment by sabre1041** [comment]
Resolved via #68
